import type { NarrativeResult } from "@/lib/narrative";

/**
 * Renders Stage 5's output: the narrative itself, plus the final
 * (post-validation) confidence score and any new flags this stage's own
 * checks raised. Deliberately visually distinct from Stage 4's panel --
 * this is prose generated by a model, not locked deterministic output,
 * and the UI should not blur that line.
 */
export default function NarrativeView({
  result,
  baselineConfidence,
}: {
  result: NarrativeResult;
  baselineConfidence: number;
}) {
  const docked = baselineConfidence - result.confidence_score;
  const newFlags = [result.forbidden_topic_hits, result.contradicted ? ["math_contradiction"] : []].flat();

  return (
    <div className="rounded-lg border border-indigo-200 bg-indigo-50/40 p-4 space-y-3">
      <div className="flex items-center justify-between">
        <span className="text-xs font-semibold text-indigo-700 uppercase tracking-wide">
          Stage 5 -- Narrative
        </span>
        <span className="text-xs text-slate-500">
          confidence:{" "}
          <span className="font-semibold text-slate-800">{result.confidence_score}</span>/100
          {docked > 0 && (
            <span className="text-red-600"> (-{docked} from Stage 4&apos;s {baselineConfidence})</span>
          )}
        </span>
      </div>

      <p className="text-sm text-slate-800 leading-relaxed italic">&ldquo;{result.narrative}&rdquo;</p>

      {newFlags.length > 0 && (
        <div>
          <div className="text-xs font-semibold text-slate-600 mb-1.5">
            Post-hoc checks caught something
          </div>
          <div className="flex flex-wrap gap-1.5">
            {newFlags.map((f) => (
              <span
                key={f}
                className="inline-block rounded bg-red-50 text-red-700 border border-red-200 px-2 py-0.5 text-[11px] font-mono"
              >
                {f}
              </span>
            ))}
          </div>
        </div>
      )}

      <p className="text-[11px] text-slate-400 border-t border-indigo-100 pt-2">
        Generated at T=0 from Stage 4&apos;s locked facts only. Independently checked against those
        same facts for unsupported topic mentions and directional contradictions before being shown
        here -- this is not the model grading its own work.
      </p>
    </div>
  );
}
